version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"             # El root del monorepo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=21"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
