version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=21"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
