packages:
  - apps/*
  - packages/*
  - packages/config/*
ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - sharp
  - unrs-resolver
